2023-07-24 21:18:40,802 ERROR MQQT connection failed
Traceback (most recent call last):
  File "/app/mqtt_module.py", line 41, in connect
    self.client.connect(self.broker_ip, self.port, 60)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.9/socket.py", line 844, in create_connection
    raise err
  File "/usr/local/lib/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host
2023-07-24 21:18:40,804 INFO MQQT successful subscribe: [('gamedata', 1), ('instruction', 1)]
